---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "frontenddev"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "frontend"
  namespace: "frontenddev"
  labels:
    app: "frontend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
      - name: "frontend-1"
        image: "gcr.io/smitbackend/doct-cbd3375-frontend:latest"
        ports:
          - containerPort: 3000
    


