apiVersion: v1
kind: Service
metadata:
  name: smitbackend-service
  namespace: smitbackendapi
  labels:
    app: smitbackend
spec:
  selector:
    app: smitbackend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
